import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Rajee',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  books: [
    {
      // _id: '1',
      name: 'Book 1',
      category: 'cate 1',
      image: '/images/book1.jpg',
      author: 'author 1',
      price: 120,
      countInStock: 10,
      description: 'once upon a time',
      slug: 'A001',
      rating: 2,
      numReviews: 5,
    },
    {
      // _id: '2',
      name: 'Book 2',
      category: 'cate 2',
      image: '/images/book2.jpg',
      author: 'author 2',
      price: 145,
      countInStock: 0,
      description: 'once upon a time in the jungle',
      slug: 'A002',
      rating: 2,
      numReviews: 5,
    },

    {
      //_id: '3',
      name: 'Book 3',
      category: 'cate 3',
      image: '/images/book3.jpg',
      author: 'author3 ',
      price: 100,
      countInStock: 10,
      description: 'once upon a time in the dessert',
      slug: 'A003',
      rating: 2,
      numReviews: 5,
    },

    {
      //_id: '4',
      name: 'Book 4',
      category: 'cate 4',
      image: '/images/book4.jpg',
      author: 'author 4',
      price: 160,
      countInStock: 10,
      description: 'once upon a time in the dessert',
      slug: 'A004',
      rating: 2,
      numReviews: 5,
    },
    {
      // _id: '5',
      name: 'Book 5',
      category: 'cate 4',
      image: '/images/book5.jpg',
      author: 'author 5',
      price: 160,
      countInStock: 10,
      description: 'once upon a time in the dessert',
      slug: 'A005',
      rating: 2,
      numReviews: 5,
    },
    {
      //_id: '6',
      name: 'Book 6',
      category: 'cate 6',
      image: '/images/book6.jpg',
      author: 'author 6',
      price: 160,
      countInStock: 10,
      description: 'once upon a time in the dessert',
      slug: 'A006',
      rating: 5,
      numReviews: 5,
    },
    {
      //_id: '7',
      name: 'Book 7',
      category: 'cate 7',
      image: '/images/book7.jpg',
      author: 'author 7',
      price: 160,
      countInStock: 10,
      description: 'once upon a time in the dessert',
      slug: 'A007',
      rating: 2.5,
      numReviews: 5,
    },
    {
      //_id: '8',
      name: 'Book 8',
      category: 'cate 8',
      image: '/images/book8.jpg',
      author: 'author 8',
      price: 160,
      countInStock: 10,
      description: 'once upon a time in the dessert',
      slug: 'A008',
      rating: 3.5,
      numReviews: 5,
    },
  ],
};
export default data;
