import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Rajee',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  books: [
    {
      // _id: '1',
      name: 'IF YOU GIVE A MOUSE A COOKIE ',
      category: 'FairyTale',
      image: '/images/book1.jpg',
      author: 'Laura Numeroff',
      price: 120,
      countInStock: 10,
      description: 'IF YOU GIVE A MOUSE A COOKIE - cartoon picture book',
      slug: 'A001',
      rating: 2,
      numReviews: 5,
    },
    {
      // _id: '2',
      name: 'THE CAT IN THE HAT',
      category: 'FairyTale',
      image: '/images/book2.jpg',
      author: 'Dr.Seuss',
      price: 145,
      countInStock: 0,
      description: 'THE CAT IN THE HAT - a comical story',
      slug: 'A002',
      rating: 2,
      numReviews: 5,
    },

    {
      //_id: '3',
      name: 'Hair Love',
      category: 'FairyTale',
      image: '/images/book3.jpg',
      author: 'Dr.Penn ',
      price: 100,
      countInStock: 10,
      description: 'Hair Love - Sentimental Story',
      slug: 'A003',
      rating: 2,
      numReviews: 5,
    },

    {
      //_id: '4',
      name: 'I Am Enough',
      category: 'FairyTale',
      image: '/images/book4.jpg',
      author: 'Grace Byers',
      price: 160,
      countInStock: 10,
      description: 'I Am Enough - Picture Book',
      slug: 'A004',
      rating: 2,
      numReviews: 5,
    },
    {
      // _id: '5',
      name: 'The Hungry Caterpillar',
      category: 'FairyTale',
      image: '/images/book5.jpg',
      author: 'Erie Carle',
      price: 160,
      countInStock: 10,
      description: 'Story of a hungry caterpillar- picture book',
      slug: 'A005',
      rating: 2,
      numReviews: 5,
    },
    {
      //_id: '6',
      name: 'First 100 Words',
      category: 'Fiction',
      image: '/images/book6.jpg',
      author: 'Priddy',
      price: 160,
      countInStock: 10,
      description: 'Kids corner',
      slug: 'A006',
      rating: 5,
      numReviews: 5,
    },
    {
      //_id: '7',
      name: 'The Arts',
      category: 'Art',
      image: '/images/book7.jpg',
      author: 'author 7',
      price: 160,
      countInStock: 10,
      description: 'The Arts - a visual encyclopedia',
      slug: 'A007',
      rating: 2.5,
      numReviews: 5,
    },
    {
      //_id: '8',
      name: 'The Story of PAINTINGS',
      category: 'Art',
      image: '/images/book8.jpg',
      author: 'Mick Manning',
      price: 160,
      countInStock: 10,
      description: 'The History of art for children',
      slug: 'A008',
      rating: 3.5,
      numReviews: 5,
    },
    {
      //_id: '8',
      name: 'Art is Fundamental',
      category: 'Art',
      image: '/images/book8.jpg',
      author: 'Eleen S. Prince',
      price: 60,
      countInStock: 10,
      description:
        'Teaching the Elements and Principles of Art in Elementary School',
      slug: 'A009',
      rating: 4.0,
      numReviews: 7,
    },
    {
      //_id: '8',
      name: 'ART Ideas',
      category: 'Art',
      image: '/images/ArtIdeas.JPG',
      author: 'John Williams',
      price: 80,
      countInStock: 10,
      description: 'The Usborne Complete Book of ART ideas',
      slug: 'A010',
      rating: 3.5,
      numReviews: 5,
    },
    {
      //_id: '8',
      name: 'BE KIND',
      category: 'Fiction',
      image: '/images/BeKind.JPG',
      author: 'JPat Zietlow Miller',
      price: 80,
      countInStock: 12,
      description: 'Cartoon picture book',
      slug: 'A011',
      rating: 3.0,
      numReviews: 9,
    },
    {
      //_id: '8',
      name: 'Gardening for Beginners',
      category: 'Gardening',
      image: '/images/GardeningforBeginners.JPG',
      author: 'Usborne Zill',
      price: 110,
      countInStock: 20,
      description: 'Gardening for Beginners',
      slug: 'A012',
      rating: 4.0,
      numReviews: 19,
    },
    {
      //_id: '8',
      name: 'Garden Time',
      category: 'Gardening',
      image: '/images/GardenTime.JPG',
      author: 'Jill McDonald',
      price: 65,
      countInStock: 15,
      description: 'Hello World, Garden Time',
      slug: 'A013',
      rating: 4.2,
      numReviews: 12,
    },
    {
      //_id: '8',
      name: 'Ginger Bread Man',
      category: 'Fiction',
      image: '/images/GingerBread.JPG',
      author: 'Gail Yerrill',
      price: 42,
      countInStock: 18,
      description: 'The Ginger Bread Man',
      slug: 'A014',
      rating: 4.5,
      numReviews: 16,
    },

    {
      //_id: '8',
      name: 'I am Simba',
      category: 'FairyTale',
      image: '/images/IamSimba.JPG',
      author: 'Gail Yerrill',
      price: 30,
      countInStock: 15,
      description: 'Disney - The Loin King',
      slug: 'A015',
      rating: 4.5,
      numReviews: 16,
    },
    {
      //_id: '8',
      name: 'Old MacDonald Had a Farm',
      category: 'FairyTale',
      image: '/images/McDonald.JPG',
      author: 'Gail Yerrill',
      price: 30,
      countInStock: 15,
      description: 'Old MacDonald Had a Farm',
      slug: 'A016',
      rating: 4.5,
      numReviews: 16,
    },
    {
      //_id: '8',
      name: 'Mindful Coloring',
      category: 'Art',
      image: '/images/MindfulColoring.JPG',
      author: 'Gail Yerrill',
      price: 70,
      countInStock: 15,
      description: 'Mindful Coloring',
      slug: 'A017',
      rating: 4.0,
      numReviews: 16,
    },
    {
      //_id: '8',
      name: 'Monet',
      category: 'Art',
      image: '/images/Monet.JPG',
      author: 'Taschen',
      price: 90,
      countInStock: 15,
      description: 'Monet- Painting',
      slug: 'A018',
      rating: 4.5,
      numReviews: 16,
    },
    {
      //_id: '8',
      name: 'New Decorating Home',
      category: 'Home',
      image: '/images/NewDecoratingHome.JPG',
      author: 'Taschen',
      price: 100,
      countInStock: 20,
      description: 'Better Homes - New Decorating Home',
      slug: 'A019',
      rating: 4.5,
      numReviews: 15,
    },
    {
      //_id: '8',
      name: ' Pablo Picasso',
      category: 'Art',
      image: '/images/Picasso.JPG',
      author: 'Pablo',
      price: 100,
      countInStock: 20,
      description: 'Getting to Know the Worlds Greatest  Artists',
      slug: 'A020',
      rating: 4.5,
      numReviews: 15,
    },
  ],
};
export default data;
