const data = {
  books: [
    {
      name: 'Book 1',
      category: 'cate 1',
      image: '/images/book1.jpg',
      price: 120,
      countInStock: 10,
      description: 'once upon a time',
      id: 'A001',
    },
    {
      name: 'Book 2',
      category: 'cate 2',
      image: '/images/book2.jpg',
      price: 145,
      countInStock: 10,
      description: 'once upon a time in the jungle',
      id: 'A002',
    },
    {
      name: 'Book 3',
      category: 'cate 3',
      image: '/images/book3.jpg',
      price: 100,
      countInStock: 10,
      description: 'once upon a time in the dessert',
      id: 'A003',
    },
    {
      name: 'Book 4',
      category: 'cate 4',
      image: '/images/book4.jpg',
      price: 160,
      countInStock: 10,
      description: 'once upon a time in the dessert',
      id: 'A004',
    },
    {
      name: 'Book 5',
      category: 'cate 4',
      image: '/images/book5.jpg',
      price: 160,
      countInStock: 10,
      description: 'once upon a time in the dessert',
      id: 'A005',
    },
    {
      name: 'Book 6',
      category: 'cate 6',
      image: '/images/book6.jpg',
      price: 160,
      countInStock: 10,
      description: 'once upon a time in the dessert',
      id: 'A006',
    },
    {
      name: 'Book 7',
      category: 'cate 7',
      image: '/images/book7.jpg',
      price: 160,
      countInStock: 10,
      description: 'once upon a time in the dessert',
      id: 'A007',
    },
    {
      name: 'Book 8',
      category: 'cate 8',
      image: '/images/book8.jpg',
      price: 160,
      countInStock: 10,
      description: 'once upon a time in the dessert',
      id: 'A008',
    },
  ],
};
export default data;
